export const cssPropertyOptions = [
  "color",
  "background-color",
  "background-image",
  "background-size",
  "background-position",
  "background-repeat",
  "background-attachment",
  "font-size",
  "font-weight",
  "font-family",
  "font-style",
  "line-height",
  "letter-spacing",
  "text-align",
  "text-decoration",
  "text-transform",
  "text-overflow",
  "white-space",
  "word-break",
  "word-wrap",
  "vertical-align",
  "padding",
  "padding-top",
  "padding-right",
  "padding-bottom",
  "padding-left",
  "margin",
  "margin-top",
  "margin-right",
  "margin-bottom",
  "margin-left",
  "border",
  "border-radius",
  "border-color",
  "border-width",
  "border-style",
  "border-top",
  "border-right",
  "border-bottom",
  "border-left",
  "box-shadow",
  "text-shadow",
  "width",
  "height",
  "min-width",
  "min-height",
  "max-width",
  "max-height",
  "box-sizing",
  "display",
  "flex",
  "flex-direction",
  "flex-wrap",
  "justify-content",
  "align-items",
  "align-self",
  "flex-grow",
  "flex-shrink",
  "flex-basis",
  "gap",
  "position",
  "top",
  "right",
  "bottom",
  "left",
  "z-index",
  "float",
  "clear",
  "opacity",
  "visibility",
  "overflow",
  "overflow-x",
  "overflow-y",
  "cursor",
  "user-select",
  "pointer-events",
  "resize",
  "outline",
  "transition",
  "transform",
  "filter",
  "will-change"
];

export const cssValueOptions: Record<string, string[]> = {
  display: ["block", "inline", "inline-block", "flex", "grid", "table", "table-cell", "table-row", "none"],
  position: ["static", "relative", "absolute", "fixed", "sticky"],
  "justify-content": ["flex-start", "center", "flex-end", "space-between", "space-around", "space-evenly"],
  "align-items": ["flex-start", "center", "flex-end", "stretch", "baseline"],
  "align-self": ["auto", "flex-start", "center", "flex-end", "stretch", "baseline"],
  "flex-direction": ["row", "row-reverse", "column", "column-reverse"],
  "flex-wrap": ["nowrap", "wrap", "wrap-reverse"],
  "flex-grow": ["0", "1", "2", "3"],
  "flex-shrink": ["0", "1", "2"],
  "flex-basis": ["auto", "0", "100%", "50%", "33.33%", "25%"],
  "text-align": ["left", "center", "right", "justify"],
  "text-decoration": ["none", "underline", "line-through", "overline"],
  "text-transform": ["none", "uppercase", "lowercase", "capitalize"],
  "text-overflow": ["clip", "ellipsis"],
  "white-space": ["normal", "nowrap", "pre", "pre-wrap", "pre-line"],
  "word-break": ["normal", "break-all", "keep-all", "break-word"],
  "word-wrap": ["normal", "break-word"],
  "vertical-align": ["baseline", "top", "middle", "bottom", "sub", "super"],
  "font-size": ["12px", "14px", "16px", "18px", "20px", "24px", "28px", "32px", "36px", "1rem", "1.5rem", "2rem"],
  "font-weight": ["400", "500", "600", "700", "bold", "normal", "lighter"],
  "font-style": ["normal", "italic", "oblique"],
  "line-height": ["1", "1.5", "2", "normal", "inherit"],
  "letter-spacing": ["normal", "0.5px", "1px", "2px", "-0.5px", "-1px"],
  cursor: ["pointer", "default", "text", "move", "not-allowed", "wait", "help", "crosshair", "grab", "grabbing"],
  overflow: ["visible", "hidden", "scroll", "auto", "clip"],
  "overflow-x": ["visible", "hidden", "scroll", "auto"],
  "overflow-y": ["visible", "hidden", "scroll", "auto"],
  "border-style": ["solid", "dashed", "dotted", "double", "groove", "ridge", "inset", "outset", "none"],
  "background-color": ["#ffffff", "#000000", "#f0f0f0", "#409eff", "transparent"],
  "background-size": ["cover", "contain", "auto", "100%", "100% 100%"],
  "background-position": ["center", "top", "bottom", "left", "right", "top left", "top right", "bottom left", "bottom right"],
  "background-repeat": ["no-repeat", "repeat", "repeat-x", "repeat-y", "space", "round"],
  "background-attachment": ["scroll", "fixed", "local"],
  color: ["#000000", "#333333", "#666666", "#999999", "#ffffff"],
  "box-shadow": ["0 1px 3px rgba(0,0,0,0.2)", "0 2px 8px rgba(0,0,0,0.15)", "none"],
  "text-shadow": ["none", "1px 1px 2px rgba(0,0,0,0.1)", "0 1px 3px rgba(0,0,0,0.3)"],
  transition: ["all 0.2s ease", "opacity 0.3s ease", "transform 0.3s ease", "none"],
  transform: ["translate(0, 0)", "scale(1)", "rotate(0deg)", "none"],
  width: ["100%", "50%", "auto", "inherit", "initial"],
  height: ["100%", "50%", "auto", "inherit", "initial"],
  "min-width": ["0", "100%", "auto"],
  "min-height": ["0", "100%", "auto"],
  "max-width": ["100%", "none", "auto"],
  "max-height": ["100%", "none", "auto"],
  "box-sizing": ["border-box", "content-box"],
  visibility: ["visible", "hidden", "collapse"],
  "pointer-events": ["auto", "none"],
  "user-select": ["none", "auto", "text", "all"],
  resize: ["none", "both", "horizontal", "vertical"],
  outline: ["none", "auto"],
  float: ["left", "right", "none"],
  clear: ["left", "right", "both", "none"],
  filter: ["none", "blur(5px)", "brightness(1)", "contrast(1)", "grayscale(100%)"],
  "will-change": ["auto", "transform", "opacity", "scroll-position"],
  padding: ["0", "4px", "8px", "12px", "16px", "20px", "24px", "1rem", "1.5rem", "2rem"],
  "padding-top": ["0", "4px", "8px", "12px", "16px", "20px", "24px", "1rem"],
  "padding-right": ["0", "4px", "8px", "12px", "16px", "20px", "24px", "1rem"],
  "padding-bottom": ["0", "4px", "8px", "12px", "16px", "20px", "24px", "1rem"],
  "padding-left": ["0", "4px", "8px", "12px", "16px", "20px", "24px", "1rem"],
  margin: ["0", "4px", "8px", "12px", "16px", "20px", "24px", "auto", "1rem", "1.5rem", "2rem"],
  "margin-top": ["0", "4px", "8px", "12px", "16px", "20px", "24px", "auto", "1rem"],
  "margin-right": ["0", "4px", "8px", "12px", "16px", "20px", "24px", "auto", "1rem"],
  "margin-bottom": ["0", "4px", "8px", "12px", "16px", "20px", "24px", "auto", "1rem"],
  "margin-left": ["0", "4px", "8px", "12px", "16px", "20px", "24px", "auto", "1rem"],
  "border-radius": ["0", "2px", "4px", "6px", "8px", "12px", "16px", "50%", "999px"],
  "border-width": ["0", "1px", "2px", "3px", "4px"],
  "border-color": ["#e0e0e0", "#d0d0d0", "#c0c0c0", "#000000", "#ffffff", "transparent"],
  "z-index": ["0", "1", "10", "100", "999", "9999", "-1", "auto"],
  opacity: ["0", "0.1", "0.2", "0.3", "0.4", "0.5", "0.6", "0.7", "0.8", "0.9", "1"],
  gap: ["0", "4px", "8px", "12px", "16px", "20px", "24px", "1rem", "1.5rem", "2rem"]
};
